// Re-export core classes for convenient access throughout the web app.
// The generated .d.mts from Kotlin/JS provides type information.
export {
  Habit,
  Entry,
  EntryList,
  Frequency,
  PaletteColor,
  HabitType,
  HabitList,
  SQLModelFactory,
  CommandRunner,
  CreateHabitCommand,
  EditHabitCommand,
  CreateRepetitionCommand,
  DeleteHabitsCommand,
  deleteHabitCommand,
  JsDatabase,
  JsDatabaseOpener,
  migrateDatabase,
  LightTheme,
  DarkTheme,
  Color,
  JsCanvas,
  JsLocalDateFormatter,
  CheckmarkButton,
  CheckmarkButtonState,
  Ring,
  HabitListHeader,
  createTaskRunner,
  createPreferences,
  createListHabitsBehavior,
  Score,
  ScoreList,
  LocalDate,
  getToday,
  setToday,
} from "uhabits-core";

export type {
  Command,
  Database,
  ModelObservable,
  ModelFactory,
  View,
  KtList,
} from "uhabits-core";
